[package]
name = "pi_agm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quanta = "0.9.3"
gmp-mpfr-sys = "1.4.7"
rug = "1.15.0"
